services:
  data_catalogue:
    build:
      dockerfile: ./apps/data_catalogue/Dockerfile
      context: ../../
      tags:
        - imago/data_catalogue:latest
    container_name: data_catalogue
    ports:
      - 3001:3000
    env_file:
      - .env.docker
    networks:
      - subnet
    depends_on:
      - postgis-18-test

  postgis-18-test:
    container_name: postgis-18-test
    image: postgis/postgis:18-3.6
    restart: always
    volumes:
      - ./data/postgres/data:/var/lib/postgresql
      - ./data/postgres/restore:/home/dump:ro
      - ./data/postgres/backup:/home/data/backup
    env_file:
      - .env.docker
    networks:
      - subnet
    ports:
      - 5439:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  subnet:
    external: true
